### ISSUE TITLE
Name resolution fails for variables declared in the behavior annex

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate2-ba#36]
Variables declared in the scope of the behavior annex (such as `count` in BA_upsample) appear to cause the AadlBaNameResolver to declare a parser failure, preventing use of behavior variables in OSATE.

```
package BA_upsample public
with Base_Types;
-- This is an example to specify the essence of multi-rate synchronous systems using up
and down sampling adapters to interface a thread a “factor” times the periods of another.

thread upsample
 features
lo: in event data port aadlinteger;
 hi: out data port aadlinteger;
 factor: constant aadlinteger => 4;
properties
Dispatch_Protocol => periodic;
end upsample;
thread implementation upsample.impl annex behavior_specification {**
states
s0: initial complete state;
variables data, count: aadlinteger => 0; transitions
-- initialization would be helpful here
s0 -[ on dispatch and count <= 0]-> s0 { count := Factor-1; lo?data; hi!data };
s0 -[ on dispatch and count > 0]-> s0 { count := count – 1; hi!data };
**};
end upsample.impl.2;
-- This is a time triggered, synchronous, implementation of the above of down-sampling
 thread downsample features
hi: in event data port aadlinteger;
 lo: out data port aadlinteger;
 factor: constant aadlinteger => 4;
properties
Dispatch_Protocol => periodic;
end downsample;
thread implementation downsample.impl 
annex behavior_specification {**
states
s0: initial complete state;
variables data, count: aadlinteger => 0; transitions
-- initialization would be helpful here
s0 -[ on dispatch and count <= 0]-> s0 { count := Factor-1; hi?data };
s0 -[ on dispatch and count > 0]-> s0 { count := count – 1; hi?data ; lo!data }; **};
end upsample.impl.2; end BA_upsample;
```

**Comment by Etienne13** [comment]
Hello,

there are several issues in the example you provided.

removing the BA subclauses, I get several errors with your AADL example. I tried to produce a correct AADL model:

package BA_upsample public
with Base_Types;
-- This is an example to specify the essence of multi-rate synchronous systems using up
-- and down sampling adapters to interface a thread a “factor” times the periods of another.

data integer extends Base_types::integer
end integer;

thread upsample
 features
   lo: in event data port integer;
   hi: out data port integer;
   factor: in data port integer;
properties
	Dispatch_Protocol => periodic;
end upsample;

thread implementation upsample.impl 
	annex behavior_specification {**
	variables 
		d, c: integer; 
	states
		s0: initial complete state;
	transitions
		-- initialization would be helpful here
		s0 -[on dispatch]-> s0 { 
			c := factor - 1; 
			lo?(d); hi!(d)
		};
		s0 -[on dispatch]-> s0 {
			c := c - 1; 
			hi!(d) 
		};
**};
end upsample.impl;

end BA_upsample;

few remarks:
 - count is the keyword of BA, please don't use it as a variable identifier;
 - data is a keyword of AADL, please don't use it as a variable identifier;
 - the BA plugin does some type checking in arithmetic operations. If you use an arithmetic operation with an integer, the BA plugin checks that all the members of the operation are of that type. It was not the case in your example but it is ok in mine; note here that aadlinteger is also an AADL keyword for the property specification language;
 - logical conjunctions are not allowed in dispatch condition (should be checked if it conforms with the standard).
 - the syntax to enqueue value x on port p, and send it, is p!(x)
 - the syntax to dequeue a value from port p and assign it to x is p?(x)

With so many syntax/semantics errors, the plugin crashes and provides very little help

Hope it helps,
Etienne.

**Comment by smithdtyler** [comment]
Etienne,

Thanks for the detailed reply. A few follow-up questions:

1.  What is the current version of the Behavior Annex? The version available from the SEI is from 2007. 

2. Why aren't conjunctions allowed in the dispatch condition?  Is it assumed that dispatch is schedule driven, and that logical conjunctions should be on state transition guards? 

3. On further digging (running OSATE from source with the debugger), I noticed that in many cases, the behavior annex produces useful errors, but they get lost before being reported to the user. I explain in more detail here: https://github.com/osate/osate2-core/issues/891

Thanks,
Tyler

**Comment by Etienne13** [comment]
Hello Tyler,

With respect to your first question, the latest version of the BA has been released in a revision of the annexes of AADL by the SAE. I guess the best way to access the latest version is to purchase it from the SAE.

For your second question, you are pretty close to the correct answer: conjunctions in the dispatch condition is not allowed to conform to the semantics of AADL: threads dispatch protocol can be "periodic", "sporadic", "hybrid", "timed" or "aperiodic". Conjunctions in the dispatch condition would make the dispatch protocol of the thread, in many cases, different than what it can be according to the AADL standard. Besides, logical conjunctions can be used on state transition guards as you mentioned.

For you third comment, thanks for checking and reporting this!

Best regards,
Etienne.
